<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Обратная связь");
?><?$APPLICATION->IncludeComponent(
	"kpi:forms.d7", 
	"feedback", 
	array(
		"AJAX_MODE" => "Y",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "Y",
		"AJAX_OPTION_STYLE" => "Y",
		"EMAIL_TO" => "",
		"EVENT_MESSAGE_ID" => array(
			0 => "30",
			1 => "",
		),
		"FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "",
		),
		"FILES_PROPERTY_CODE" => array(
			0 => "FILE",
			1 => "",
		),
		"FORM_ID" => "feedback",
		"FORM_SUBMIT" => "Отправить",
		"FORM_SUBTITLE" => "",
		"FORM_TITLE" => "Форма обратной связи",
		"FORM_TITLE_FOR_EMAIL" => "",
		"IBLOCK_ID" => "7",
		"IBLOCK_TYPE" => "forms",
		"NEW_NAME_COMPANY" => "Компания",
		"NEW_NAME_EMAIL" => "E-mail",
		"NEW_NAME_NAME" => "ФИО",
		"NEW_NAME_PREVIEW_TEXT" => "Сообщение",
		"OK_TEXT" => "<p>Вы также можете связаться с нами по телефону</p>",
		"OK_TEXT_TITLE" => "<h2>Спасибо!</h2><h3>Ваше сообщение отправлено.</h3>",
		"PROPERTY_CODE" => array(
			0 => "PHONE",
			1 => "",
		),
		"REQUIRED_FIELDS" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "",
		),
		"REQUIRED_PROPERTY_CODE" => array(
			0 => "PHONE",
			1 => "",
		),
		"SEND_TO_ADMIN" => "Y",
		"SEND_TO_USER" => "N",
		"SORT_COMPANY" => "20",
		"SORT_EMAIL" => "10",
		"SORT_NAME" => "1",
		"SORT_PREVIEW_TEXT" => "3",
		"TEXT_APPEAL_TO_USER" => "",
		"TEXT_MESSAGE_TO_USER" => "",
		"COMPONENT_TEMPLATE" => "feedback",
		"NEW_NAME_PHONE" => "Телефон",
		"SORT_PHONE" => "2",
		"USE_PLACEHOLDER" => "Y",
		"PLACEHOLDER_NAME" => "Иванов Сергей Петрович",
		"PLACEHOLDER_PREVIEW_TEXT" => "Текст сообщения...",
		"PLACEHOLDER_PHONE" => "+7 ___ ___ - __ - __",
		"PLACEHOLDER_FILE" => "Файл",
		"NEW_NAME_FILE" => "Прикрепить файл",
		"SORT_FILE" => "4",
		"KPI_BACK_BTN_TEXT" => "Назад",
		"KPI_BACK_BTN_LINK" => "/ru/contacts/",
		"USE_SMS_CONFIRM" => "N",
		"OK_PHONES" => array(
			0 => "+7 (7122) 30 65 00",
			1 => "",
		),
		"OK_EMAILS" => array(
			0 => "info@kpi.kz",
			1 => "",
			2 => "",
		),
		"OK_LOGO" => "/local/templates/main_kpi/assets/img/svg/logo_3.svg",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO"
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>