<?
$aMenuLinks = Array(
	Array(
		"Гостиницы", 
		"/ru/sobytiya-i-meropriyatiya/kruglyy-stol-kadry-gazoneftekhimii/marshruty/gostinitsy", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Вокзал", 
		"/ru/sobytiya-i-meropriyatiya/kruglyy-stol-kadry-gazoneftekhimii/marshruty/vokzal", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Аэропорт", 
		"/ru/sobytiya-i-meropriyatiya/kruglyy-stol-kadry-gazoneftekhimii/marshruty/aeroport", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Центр Н.Балгимбаева", 
		"/ru/sobytiya-i-meropriyatiya/kruglyy-stol-kadry-gazoneftekhimii/marshruty/tsentr-im-n-balgimbaeva", 
		Array(), 
		Array(), 
		"" 
	)
);
?>