<?
$aMenuLinks = Array(
	Array(
		"Главные темы", 
		"/ru/sobytiya-i-meropriyatiya/kruglyy-stol-kadry-gazoneftekhimii/glavnye-temy", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Участники", 
		"/ru/sobytiya-i-meropriyatiya/kruglyy-stol-kadry-gazoneftekhimii/uchastniki", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Программа", 
		"/ru/sobytiya-i-meropriyatiya/kruglyy-stol-kadry-gazoneftekhimii/programma", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Маршруты", 
		"/ru/sobytiya-i-meropriyatiya/kruglyy-stol-kadry-gazoneftekhimii/marshruty", 
		Array(), 
		Array(), 
		"" 
	)
);
?>